#!/usr/bin/env bash

# Deploys a domain controller.  
#  Steps:
#       1.  Calls terraform wrapper (apply.sh) to create the VM
#       2.  Then calls the ansible wrapper (deploy-dc.sh); 
#              each step has its own logs (/srv/logs)

# ================================================================================================
# Notes:  
#     - Never automate with a domain admin account in prod; this is a lab exercise.
#     - Production deployments use tighter controls around credentials and promoting DCs.
#     - Credential management is on the roadmap (Hashicorp vault?)
#     - I could have also automated all passwords, hostnames (etc), but, DCs are very stateful, 
#           and core services of my lab (I want a human to verify, more than once, before promoting)
# ================================================================================================

# Prerequisites: Add host to terraform.tfvars (Ansible inventory is auto-generated by Terraform).
# 
# Usage (using dc03 as an example, so the host would be INFUS103DC03):
#   ./deploy-dc.sh dc03 \
#     -e domain_admin_user='AD\Administrator' \
#     -e domain_admin_password='<password>' \
#     -e dsrm_password='<dsrm_password>'

set -euo pipefail

#  test number of arguments
if [[ $# -lt 1 ]]; then
    
    echo "Usage: $0 <dc-name> [ansible extra vars/options]"
    echo "Example: $0 dc03 -e domain_admin_user='AD\Administrator' -e domain_admin_password='<password>' -e dsrm_password='<password>'"

    exit 1
fi

#  build variables from arguments
DC_NAME="$1"
shift

HOSTNAME="INFUS103${DC_NAME^^}"
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

#  Call Terraform to create VM
cd "${REPO_ROOT}/terraform/us103/domain-controllers" && ./apply.sh -target="module.dc[\"${DC_NAME}\"]" -target="local_file.ansible_inventory"

#  Call Ansibe to configure DC
echo "============================================================================="
echo "!!!-WARNING-!!!"
echo "PUTTING IN THE TEMPLATE PASSWORD WILL PROMOTE $HOSTNAME TO A DOMAIN CONTROLLER"
echo "============================================================================="

cd "${REPO_ROOT}/ansible" && scripts/deploy-dc.sh --limit "${HOSTNAME}" "$@"