apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

  # Namespace
  
  # Prometheus
  
  # Grafana
resources:
- namespace.yaml
- prometheus/rbac.yaml
- prometheus/configmap.yaml
- prometheus/deployment.yaml
- prometheus/service.yaml
- grafana/configmap.yaml
- grafana/deployment.yaml
- grafana/service.yaml
- grafana/ingress.yaml


commonAnnotations:
  environment: homelab
  maintained-by: bryan
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: monitoring-stack
