apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This sets the namespace on namespaced resources, but does not create it.
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - ingress.yaml
  - repo-secret.yaml
  - cluster-us103-k3s01.yaml

patchesJson6902:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
      namespace: argocd
    patch: |
      - op: add
        path: /data
        value: {}
      - op: add
        path: /data/server.insecure
        value: "true"

  - target:
      version: v1
      kind: Service
      name: argocd-server
      namespace: argocd
    patch: |
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: replace
        path: /spec/ports
        value:
          - name: http
            port: 80
            targetPort: 8080

