apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Ensure Namespace exists first
  - namespace.yaml

  # Argo CD upstream install
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

  # Your custom resources
  - ingress.yaml
  - repo-secret.yaml
  - cluster-us103-k3s01.yaml

# Use patches (JSON6902) to modify upstream objects to avoid ID conflicts
patches:
  # Force argocd-server Service to ClusterIP:80 -> 8080
  - target:
      version: v1
      kind: Service
      name: argocd-server
      namespace: argocd
    patch: |
      - op: replace
        path: /spec/type
        value: ClusterIP
      - op: replace
        path: /spec/ports
        value:
          - name: http
            port: 80
            targetPort: 8080

  # Set dark theme on argocd-cm without creating a second ConfigMap
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
    patch: |
      - op: add
        path: /data/ui.theme
        value: dark

  # Set admin password on argocd-secret without creating a second Secret
  - target:
      version: v1
      kind: Secret
      name: argocd-secret
      namespace: argocd
    patch: |
      - op: add
        path: /stringData
        value: {}
      - op: add
        path: /stringData/admin.password
        value: $2b$10$sQzrNdJzBs2qH96PjJfzGO5FOghaB/qoeD1erGy.Z0aBAxr7vrwnO
      - op: add
        path: /stringData/admin.passwordMtime
        value: "2025-08-19T22:13:20.818881Z"
