apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  template:
    spec:
      volumes:
      - name: prometheus-storage
        $patch: replace
        persistentVolumeClaim:
          claimName: prometheus-storage