#  Package names specific to RedHat based distros (Fedora, Rocky, Alma, etc)
#  Filename must match ansible_facts.os_family exactly.

linux_packages_family:
  - fuse-sshfs
  - openssh-clients
  - remmina-plugins-rdp
  - vim-enhanced
