apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie-app
  name: mealie-deploy
  namespace: mealie-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-app
  template:
    metadata:
      labels:
        app: mealie-app
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.0.1
        name: mealie-cont
        ports:
          - containerPort: 9000
        volumeMounts:
          - mountPath: /app/data
            name: mdata
      volumes:
        - name: mdata
          persistentVolumeClaim:
            claimName: mealie-pvc
