apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie-app
  name: mealie-svc
  namespace: mealie-ns
spec:
  type: ClusterIP
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie-app