# k8s/platform/rancher/gitops/rancher-app.yaml
# ArgoCD Application for GitOps management of Rancher

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  labels:
    app.kubernetes.io/name: rancher
    app.kubernetes.io/component: platform
    environment: us103
    cluster: kubeadm01
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    chart: rancher
    targetRevision: 2.11.3
    helm:
      valueFiles:
      - values.yaml
      values: |
        # Rancher configuration for infUTable homelab
        hostname: rancher.us103kubeadm01.infutable.com
        
        # Bootstrap password (change in production!)
        bootstrapPassword: "infUtableR@ncher2024!"
        
        # Ingress configuration
        ingress:
          ingressClassName: nginx
          tls:
            source: rancher
            secretName: tls-rancher-ingress
        
        # Let's Encrypt configuration
        letsEncrypt:
          email: admin@infutable.com
          environment: staging
          ingress:
            class: nginx
        
        # Resource configuration
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        
        # Single replica for homelab
        replicas: 1
        
        # Disable PSP for modern Kubernetes
        global:
          cattle:
            psp:
              enabled: false
        
        # Enable monitoring integration
        monitoring:
          enabled: true
        
        # Basic audit logging
        auditLog:
          level: 1
          maxAge: 30
          maxBackup: 10
          maxSize: 100

  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health checks
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas

  # Notification configuration (optional)
  revisionHistoryLimit: 10

---
# Optional: AppProject for better organization
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
  labels:
    environment: us103
spec:
  description: Platform services for infUTable infrastructure
  
  sourceRepos:
  - 'https://releases.rancher.com/server-charts/stable'
  - 'https://github.com/1BSmithITGuy/infutable-infra'
  
  destinations:
  - namespace: 'cattle-system'
    server: https://kubernetes.default.svc
  - namespace: 'rancher-*'
    server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: 'apps'
    kind: '*'
  - group: 'batch'
    kind: '*'
  - group: 'extensions'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: 'cert-manager.io'
    kind: '*'

  roles:
  - name: platform-admin
    description: Platform administrator role
    policies:
    - p, proj:platform:platform-admin, applications, *, platform/*, allow
    - p, proj:platform:platform-admin, repositories, *, *, allow
    groups:
    - infutable:platform-admins