# Group hierarchy for site US103
#
# Defines parent/child group relationships.
# Host membership is in separate files (per role). Server inventory is managed
# by terraform; workstation inventory is hand maintained (physical machines).


all:
  children:

    windows:
      children:
        domain_controllers: {}
        windows_workstations: {}

    linux:
      children:
        linux_workstations: {}

    workstations:
      children:
        linux_workstations: {}
        windows_workstations: {}
