{
 "title": "US103-Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "prom", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "bsus103k-8m01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}\n- node_boot_time_seconds{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (avg_over_time(node_memory_SwapTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval]) > bool 0)\n* (\n  1 -\n  avg_over_time(node_memory_SwapFree_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n  /\n  clamp_min(avg_over_time(node_memory_SwapTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval]), 1)\n)\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "/ total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}\n"
    }
   ]
  },
  { "title": "bsus103k-8w01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}\n- node_boot_time_seconds{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (avg_over_time(node_memory_SwapTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval]) > bool 0)\n* (\n  1 -\n  avg_over_time(node_memory_SwapFree_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n  /\n  clamp_min(avg_over_time(node_memory_SwapTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval]), 1)\n)\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "/ total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}\n"
    }
   ]
  },
  { "title": "bsus103k-8w02", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}\n- node_boot_time_seconds{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (avg_over_time(node_memory_SwapTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval]) > bool 0)\n* (\n  1 -\n  avg_over_time(node_memory_SwapFree_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n  /\n  clamp_min(avg_over_time(node_memory_SwapTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval]), 1)\n)\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "/ total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}\n"
    }
   ]
  },
  { "title": "bsus103km01 (k3s)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"k3s-nodes\", instance=\"bsus103km01\"}\n- node_boot_time_seconds{job=\"k3s-nodes\", instance=\"bsus103km01\"}\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg_over_time(node_memory_SwapTotal_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n  -\n  avg_over_time(node_memory_SwapFree_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n)\n/\navg_over_time(node_memory_SwapTotal_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n* 100\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "/ total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\", mountpoint=\"/\", fstype!=\"rootfs\"}\n"
    }
   ]
  }
 ]
}