# Tasks to add the Google Chrome repo on the Debian family
# File has caps to match Ansible facts format

# Chrome writes its own repo file with a different name value when upgrading, which would be flagged
# "changed" on scheduled ansible runs. stat tests if the repo file exists, and if it does, ansible
# will not add/modify the existing repo file.

---
- name: Download Google signing key
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /etc/apt/keyrings/google-chrome.asc
    mode: "0644"
  become: true

- name: Check if Chrome repo exists
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/google-chrome.list
  register: chrome_repo

- name: Add the Chrome repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.asc] https://dl.google.com/linux/chrome/deb/ stable main"
    filename: google-chrome
    state: present
  become: true
  when: not chrome_repo.stat.exists
