apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  namespace: argocd
labels:
  app.kubernetes.io/name: argocd-cmd-params-cm
  app.kubernetes.io/part-of: argocd
data:
  # Tell the API server to serve HTTP (no TLS) so the NGINX ingress can talk plain HTTP
  server.insecure: "true"
  # Optional: if you want to disable the TLS redirect behavior entirely
  # server.disable.auth: "false"

