#cloud-config
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - 10.0.2.20/27
      gateway4: 10.0.2.1
      nameservers:
        search: [ad.infutable.com]
        addresses:
          - 10.0.1.2
          - 10.0.1.3