apiVersion: v1
kind: Service
metadata:
  name: solar-system-service
  labels:
    app: solar-system
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: solar-system
