apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  template:
    spec:
      volumes:
      - name: prometheus-storage
        emptyDir: null
        persistentVolumeClaim:
          claimName: prometheus-storage
