{
 "title": "US103-Overview v2",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "prom", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "bsus103k-8m01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n  irate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "sum by(instance)(\n  irate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}\n- node_boot_time_seconds{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.20:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(\n  irate(node_disk_read_time_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n  /\n  irate(node_disk_reads_completed_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "clamp_min(\n  irate(node_disk_write_time_seconds_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval])\n  /\n  irate(node_disk_writes_completed_total{job=\"node-exporter\", instance=\"10.0.2.20:9100\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  },
  { "title": "bsus103k-8w01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n  irate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "sum by(instance)(\n  irate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}\n- node_boot_time_seconds{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.22:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(\n  irate(node_disk_read_time_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n  /\n  irate(node_disk_reads_completed_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "clamp_min(\n  irate(node_disk_write_time_seconds_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval])\n  /\n  irate(node_disk_writes_completed_total{job=\"node-exporter\", instance=\"10.0.2.22:9100\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  },
  { "title": "bsus103k-8w02", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n  irate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "sum by(instance)(\n  irate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}\n- node_boot_time_seconds{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"10.0.2.23:9100\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(\n  irate(node_disk_read_time_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n  /\n  irate(node_disk_reads_completed_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "clamp_min(\n  irate(node_disk_write_time_seconds_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval])\n  /\n  irate(node_disk_writes_completed_total{job=\"node-exporter\", instance=\"10.0.2.23:9100\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  },
  { "title": "bsus103km01 (k3s - Prod)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n  irate(node_network_receive_bytes_total{job=\"k3s-nodes\", instance=\"bsus103km01\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "sum by(instance)(\n  irate(node_network_transmit_bytes_total{job=\"k3s-nodes\", instance=\"bsus103km01\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"k3s-nodes\", instance=\"bsus103km01\"}\n- node_boot_time_seconds{job=\"k3s-nodes\", instance=\"bsus103km01\"}\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"k3s-nodes\", instance=\"bsus103km01\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(\n  irate(node_disk_read_time_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n  /\n  irate(node_disk_reads_completed_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "clamp_min(\n  irate(node_disk_write_time_seconds_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval])\n  /\n  irate(node_disk_writes_completed_total{job=\"k3s-nodes\", instance=\"bsus103km01\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  },
  {
   "title": "bsus103k-mgt01 (k3s - Management)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\", mode!=\"idle\"}[$__rate_interval])\n  )\n  /\n  on(instance) group_left\n  sum by(instance) (\n    irate(node_cpu_seconds_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n  )\n) * 100\n"
    }
   ]
  },
  {
   "title": "CPU-5 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPU-15 min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n* 100\n/ on(instance) group_left\nsum by (instance)(\n  irate(node_cpu_seconds_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance)(\n  irate(node_network_receive_bytes_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "sum by(instance)(\n  irate(node_network_transmit_bytes_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\", device!~\"^(lo|veth.*|cni.*|flannel.*|docker.*|br-.*)$\"}[$__rate_interval]) * 8\n)\n",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_memory_MemAvailable_bytes{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_memory_MemTotal_bytes{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}\n- node_boot_time_seconds{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}\n"
    }
   ]
  },
  {
   "title": "/ Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\n  avg_over_time(node_filesystem_avail_bytes{job=\"rancher-node\", instance=\"bsus103k-mgt01\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval]) * 100\n  /\n  avg_over_time(node_filesystem_size_bytes{job=\"rancher-node\", instance=\"bsus103k-mgt01\", mountpoint=\"/\", fstype!=\"rootfs\"}[$__rate_interval])\n)\n"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}) by (cpu))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "description": "The average time for requests issued to the device to be served. This includes the time spent by the requests in queue and the time spent servicing them.",
   "gridPos": { "h": 4, "w": 12, "x": 9, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "clamp_min(\n  irate(node_disk_read_time_seconds_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n  /\n  irate(node_disk_reads_completed_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Read wait time avg"
    },
    {
     "expr": "clamp_min(\n  irate(node_disk_write_time_seconds_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval])\n  /\n  irate(node_disk_writes_completed_total{job=\"rancher-node\", instance=\"bsus103k-mgt01\"}[$__rate_interval]),\n0)\n",
     "legendFormat": "{{device}} - Write wait time avg"
    }
   ]
  }
 ]
}